config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    get 'operations', on: :member
    resources :maintenances, shallow: true, except: :edit  do
      resources :operations, shallow: true, except: :show
    end
  end

  get 'operation/titles', to: 'operations#titles'

  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_maintenance_overview.html.slim
.row id="row_#{dom_id(mt)}" class="maintenance #{cycle 'odd', 'even'}"
  .col-10
    = link_to "#{mt.title || '(no title)'}", maintenance_path(mt), class: 'maintenance-link stretched-link text-decoration-none align-middle'
    h6.text-muted ##{mt.id.to_s.rjust(3,'0')}: [#{mt.completed_on}: #{mt.completed_mirage.to_s.rjust(5,'0')}km]
  .col-2
    .dropdown.float-right
      a.btn.btn-secondary.btn-sm.dropdown-toggle.maintenance-more href="#" role="button" id="maintenanceMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
        | More
      .dropdown-menu.dropdown-menu-right aria-labblledby='maintenanceMenuLink'
        = link_to "Show", maintenance_path(mt), class: 'dropdown-item'
        = link_to "Delete", maintenance_path(mt), method: :delete, class: 'dropdown-item', remote: true, 
                  data: { "confirm": "Are you sure?\nAll operations in this maintenance will also be deleted.\nThis cannot be undone.", "disable-with": "Deleting" }

app/views/home/index.html.slim
h3 
  = "Hello! #{current_user.email}"
h4 Your Cars and Maintenances
- current_user.cars.each do |car|
  .card.mb-2
    .card-body id="row_#{dom_id(car)}_and_maintenance"
      .row id="row_#{dom_id(car)}"
        h4.col.card-title = car.name
        .col-auto.float-right
          .row
            .col-12
              = link_to 'Show operatoin history', operations_car_path(car), class: 'btn btn-sm btn-primary col-sm-auto'
              = link_to "Add maintenance record", new_car_maintenance_path(car), class: 'btn btn-sm btn-primary col-sm-auto'
      .row.mb-3
        .col-12
      .row
        h5.col-12.card-subtitle
          | Recent Maintenances
      = render(partial: 'maintenance_overview', 
               collection: car.maintenances.order(completed_on: :desc).limit(5), 
               as: :mt) || content_tag('div', "(No maintenance record)", class: 'text-muted')