config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    get 'operations', on: :member
    resources :maintenances, shallow: true, except: :edit  do
      resources :operations, shallow: true, except: :show
    end
  end

  get 'operation/titles', to: 'operations#titles'

  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/maintenance.rb
class Maintenance < ApplicationRecord
  belongs_to :car, inverse_of: :maintenances
  has_one :user, through: :car, inverse_of: :maintenances
  has_many :operations, inverse_of: :maintenance, dependent: :destroy
  accepts_nested_attributes_for :operations, allow_destroy: true

end

app/controllers/maintenances_controller.rb
class MaintenancesController < ApplicationController
  before_action :set_maintenance, only: [:show, :edit, :update, :destroy]
  before_action :get_car, only: [:index, :create, :new]

  # GET /maintenances
  # GET /maintenances.json
  def index
    @maintenances = @car.maintenances
  end

  # GET /maintenances/1
  # GET /maintenances/1.json
  def show
  end

  # GET /maintenances/new
  def new
    @maintenance = @car.maintenances.build
  end

  # POST /maintenances
  # POST /maintenances.json
  def create
    @maintenance = @car.maintenances.build(maintenance_params)

    respond_to do |format|
      if @maintenance.save
        format.html { redirect_to @maintenance, notice: 'Maintenance was successfully created.' }
        format.json { render :show, status: :created, location: @maintenance }
      else
        format.html { render :new }
        format.json { render json: @maintenance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintenances/1
  # PATCH/PUT /maintenances/1.json
  def update
    respond_to do |format|
      if @maintenance.update(maintenance_params)
        format.html { redirect_to @maintenance, notice: 'Maintenance was successfully updated.' }
        format.json { render :show, status: :ok, location: @maintenance }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @maintenance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintenances/1
  # DELETE /maintenances/1.json
  def destroy
    @maintenance.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to root_path, notice: 'Maintenance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_maintenance
      @maintenance = Maintenance.find(params[:id])
    end

    def get_car
      @car = Car.find(params[:car_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def maintenance_params
      params.require(:maintenance)
            .permit(:car_id, :title, :completed_on, :completed_mirage, :description, operations_attributes: [:id, :title, :description])
    end
end

app/views/maintenances/_fieldset.html.slim
fieldset.maintenance-form-fields
  .form-row.form-group
    .col
      = form.text_field :title, required: true, placeholder: 'title', class: 'form-control form-control-lg'
  .form-row.form-group
    .form-inline
      .col-auto
        = form.label :completed_on, class: 'col-form-label col-form-label-lg'
      .col-auto
        = form.date_field :completed_on, class: "form-control"
      .col-auto
        .input-group
          .input-group-prepend
            = form.label :completed_mirage, '@ ',class: 'col-form-label col-form-label-lg input-group-text'
          = form.number_field :completed_mirage, placeholder: '15000', class: 'form-control'
      .col-auto
        = form.label :completed_mirage, ' km',class: 'col-form-label col-form-label-lg'
  .form-row.form-group
    .col
      = form.text_field :description, placeholder: 'description', class: 'form-control'

app/views/maintenances/_maintenance.html.slim
div#overview-wrapper.row
  div#maintenance-overview.maintenance.col-12
    h2
      | [Maintenance] #{maintenance.title}
      span.badge.badge-secondary.ml-3 = maintenance.car.name

    h4 Completed on #{maintenance.completed_on} @ #{maintenance.completed_mirage}km

    p = maintenance.description || "(No Description)"
    button.btn.btn-primary[type="button" data={collapse_target: "#maintenance-overview", expand_target: "#maintenance_form", collapse_parent: '#overview-wrapper'}]
      | Edit

  div#maintenance_form.maintenance.jr-hidden.col-12
    = form_with model: maintenance do |f|
      = render partial: 'fieldset', locals: {form: f}
      .btn-group
        button.btn.btn-primary[type="button" data={collapse_target: "#maintenance_form", expand_target: "#maintenance-overview", collapse_parent: '#overview-wrapper'}] 
          | Cancel
        = f.submit class: 'btn btn-primary'      

app/views/maintenances/_operation_fieldset.html.slim
.col
  fieldset
    .form-row.form-group
      .col-sm-5.col-12.form-group = form.text_field :title, class: 'form-control', placeholder: 'title', autocomplete: 'off', data: {'operation-title-autocomplete': true}  
      .col-sm-7.col-12.form-group = form.text_field :description, class: 'form-control', placeholder: 'description'

app/views/maintenances/destroy.js.erb
$("#row_<%= dom_id(@maintenance) %>")
    .animate(
        {opacity: 'hide', height: 'hide'},
        {complete: () => { $("#row_<%= dom_id(@maintenance) %>").remove(); }}
    );

app/views/maintenances/index.html.slim
h1 Listing maintenances

table
  thead
    tr
      th Car
      th Title
      th Completed on
      th Completed mirage
      th
      th
      th

  tbody
    - @maintenances.each do |maintenance|
      tr
        td = maintenance.car
        td = maintenance.title
        td = maintenance.completed_on
        td = maintenance.completed_mirage
        td = link_to 'Show', maintenance
        td = link_to 'Edit', edit_maintenance_path(maintenance)
        td = link_to 'Destroy', maintenance, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Maintenance', new_maintenance_path

app/views/maintenances/new.html.slim
h1 Record maintenance

= form_with model: [@car, @maintenance] do |f|
  - if @maintenance.errors.any?
    #error_explanation
      h2 = "#{pluralize(@maintenance.errors.count, "error")} prohibited this maintenance from being saved:"
      ul
        - @maintenance.errors.full_messages.each do |message|
          li = message
  = render partial: 'fieldset', locals: {form: f}
  hr
  h4
    | Operations
    = link_to_add_fields "Add", f, :operations, 'operation_fields', 'btn btn-sm btn-primary ml-2'
  div#operation_fields

  .actions = f.submit class: 'btn btn-primary'

= link_to_home

app/views/maintenances/show.html.slim
p#notice = notice

= render @maintenance 

h3.mt-3 Operations

= form_with model: [@maintenance, Operation.new], namespace: 'new_form' do |f|
  .form-row
    = render 'operation_fieldset', form: f
    .col-md-3.col-sm-4.col-5
      .form-row
        .form-group.col
          = f.submit 'Create', class: 'btn btn-primary btn-block'
div#operations
  = render @maintenance.operations
= link_to_home

app/views/maintenances/update.js.erb
$("#overview-wrapper")
    .animate(
        {opacity: 'hide', height: 'hide'},
        {complete: function(){ 
                $("#overview-wrapper").replaceWith(
                    $("<%= escape_javascript (render @maintenance) %>").hide()
                );
                $("#overview-wrapper").animate({opacity: 'show', height: 'show'},);
        }}
    );