config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    get 'operations', on: :member
    resources :maintenances, shallow: true, except: :edit  do
      resources :operations, shallow: true, except: :show
    end
  end

  get 'operation/titles', to: 'operations#titles'

  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user, inverse_of: :cars
  has_many :maintenances, inverse_of: :car, dependent: :destroy
  has_many :operations, through: :maintenances, inverse_of: :car
  accepts_nested_attributes_for :maintenances, allow_destroy: true
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy, :operations]

  # GET /cars
  # GET /cars.json
  def index
    @cars = current_user.cars
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = current_user.cars.build
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = current_user.cars.build(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  def operations
    if operations_params[:q]
      @operations = @car.operations.by_title_like(operations_params[:q])
    else
      @operations = @car.operations
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = current_user.cars.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:user_id, :name)
    end

    def operations_params
      params.permit(:q)
    end
end

app/views/cars/_car.html.slim
  .div[id="row_#{dom_id(car)}"]
    .row.col-12
      h3
        span.col-4 = car.name
      .div[id="edit_#{dom_id(car)}"]
        .form-row.col-12[id="overview_#{dom_id(car)}"]
          span.btn-group.col-8
            button.btn.btn-primary.col[type="button" data={collapse_target: "#overview_#{dom_id(car)}",
                                                      expand_target: "#edit_form_#{dom_id(car)}",
                                                      collapse_parent: "#edit_#{dom_id(car)}", }]
              | Edit
            = link_to "delete", car_path(car), class: 'btn btn-primary col',
                      method: :delete, remote: true, data: { "confirm": "Are you sure to delete?", "disable-with": "Deleting" }
    .jr-hidden[id="edit_form_#{dom_id(car)}"]
      = form_with model: car, namespace: "edit_form_#{dom_id(car)}" do |f|
        .form-row
          .form-group.col-4 = f.text_field :name, class: 'form-control', placeholder: 'name'
          .form-group.col-2.btn-group
            button.btn.col.btn-info[type="button" data={collapse_target: "#edit_form_#{dom_id(car)}",
                                                    expand_target: "#overview_#{dom_id(car)}",
                                                    collapse_parent: "#edit_#{dom_id(car)}", }]
              | Cancel
            = f.submit 'Update', class: 'btn btn-info col'

app/views/cars/_form.html.slim
= form_for @car do |f|
  - if @car.errors.any?
    #error_explanation
      h2 = "#{pluralize(@car.errors.count, "error")} prohibited this car from being saved:"
      ul
        - @car.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/cars/destroy.js.erb
$("#row_<%= dom_id(@car) %>_and_maintenance")
    .animate(
        {opacity: 'hide', height: 'hide'},
        {complete: () => { $("#row_<%= dom_id(@car) %>_and_maintenance").remove(); }}
    );

app/views/cars/edit.html.slim
h1 Editing car

== render 'form'

=> link_to 'Show', @car
'|
=< link_to 'Back', cars_path

app/views/cars/index.html.slim
h1 Manage Your cars
= link_to 'Add new car', new_car_path, class: 'btn btn-primary'

= render @cars
br

= link_to_home

app/views/cars/new.html.slim
h1 New car

== render 'form'

= link_to 'Back', cars_path

app/views/cars/operations.html.slim
h1 Operations history for #{@car.name}

= form_with(url: operations_car_path(@car), method: "get", local: true, html: {class: 'form-inline'}) do
  .form-group
    .form-row
      .col-auto
        = text_field_tag(:q, nil, class: 'form-control', placeholder: 'filter', autocomplete: 'off', data: {'operation-title-autocomplete': true})
      .col-auto
        = submit_tag("GO", class: 'btn btn-primary') 

- @operations.each do |o|
  .row class="car-operation #{cycle 'odd', 'even'}"
    .col-md-4 = o.title
    .col-md-auto #{o.maintenance.completed_on} @#{o.maintenance.completed_mirage}km
    .col-md-auto = o.description

= link_to_home

app/views/cars/show.html.slim
p#notice = notice

p
  strong User:
  = @car.user
p
  strong Name:
  = @car.name

=> link_to 'Edit', edit_car_path(@car)
'|
=< link_to 'Back', cars_path

app/views/cars/update.js.erb
$("#row_<%= dom_id(@car) %>")
    .animate(
        {opacity: 'hide', height: 'hide'},
        {complete: function(){ 
                $("#row_<%= dom_id(@car) %>").replaceWith(
                    $("<%= escape_javascript (render @car) %>").hide()
                );
                $("#row_<%= dom_id(@car) %>").animate({opacity: 'show', height: 'show'},);
        }}
    );