config/routes.rb
Rails.application.routes.draw do
  resources :cars do
    get 'operations', on: :member
    resources :maintenances, shallow: true, except: :edit  do
      resources :operations, shallow: true, except: :show
    end
  end

  get 'operation/titles', to: 'operations#titles'

  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "home#index"
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :maintenance, inverse_of: :operations
  has_one :car, through: :maintenance, inverse_of: :operations
  has_one :user, through: :car, inverse_of: :operations

  scope :by_title_like, lambda { |q|
    where('lower(operations.title) LIKE :q', { q: "#{sanitize_sql_like(q.downcase)}%"})
  }
end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:edit, :update, :destroy]
  before_action :get_maintenance, only: [:index, :create, :new]

  # GET /operations
  # GET /operations.json
  def index
    @operations = @maintenance.operations
  end

  # GET /operations/new
  def new
    @operation = @maintenance.operations.build()
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = @maintenance.operations.build(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to @operation, notice: 'Operation was successfully created.' }
        format.js
      else
        format.html { render :new }
        format.js
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'Operation was successfully destroyed.' }
      format.js
    end
  end
  
  def titles
    # TODO this is slow because it joins oeration, maintenance, car and user
    q = ActiveRecord::Base.sanitize_sql_like(titles_params[:q])
    render plain: {titles: current_user.operations.by_title_like(q).order(title: "ASC").distinct.pluck(:title)}.to_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    def get_maintenance
      @maintenance = Maintenance.find(params[:maintenance_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operation_params
      params.require(:operation).permit(:maintenance_id, :title, :description)
    end

    def titles_params
      params.permit(:q, :format)
    end
end

app/views/operations/_form.html.slim
= form_for [@maintenance, @operation]   do |f|
  - if @operation.errors.any?
    #error_explanation
      h2 = "#{pluralize(@operation.errors.count, "error")} prohibited this operation from being saved:"
      ul
        - @operation.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :maintenance
    = f.text_field :maintenance
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .actions = f.submit

app/views/operations/_operation.html.slim
div[id=("row_#{dom_id(operation)}")]
  .form-row[id="overview_#{dom_id(operation)}"]
    .col
      .form-row
        .col-sm-5.col-12 = operation.title
        .col-sm-7.col-12 = operation.description || '(no description)'
    .col-md-3.col-sm-4.col-5
      .form-row
        .col-12.form-group.btn-group
          button.btn.btn-primary.col[type="button" data={collapse_target: "#overview_#{dom_id(operation)}",
                                                    expand_target: "#edit_form_#{dom_id(operation)}",
                                                    collapse_parent: "#row_#{dom_id(operation)}", }]
            | Edit
          = link_to "delete", operation_path(operation), class: 'btn btn-primary col',
                    method: :delete, remote: true, data: { "confirm": "Are you sure to delete?", "disable-with": "Deleting" }
  .jr-hidden[id="edit_form_#{dom_id(operation)}"]
    = form_with model: operation, namespace: "edit_form_#{dom_id(operation)}" do |f|
      .form-row
        = render 'operation_fieldset', form: f
        .col-md-3.col-sm-4.col-5
          .form-row
            .col-12.form-group.btn-group
              button.btn.col.btn-info[type="button" data={collapse_target: "#edit_form_#{dom_id(operation)}",
                                                      expand_target: "#overview_#{dom_id(operation)}",
                                                      collapse_parent: "#row_#{dom_id(operation)}", }]
                | Cancel
              = f.submit 'Update', class: 'btn btn-info col'

app/views/operations/create.js.erb
$("<%= escape_javascript(render @operation) %>")
  .hide()
  .prependTo("#operations")
  .animate({opacity: 'show', height: 'show'}, complete = () => {
    $('#new_form_operation_title').val("");
    $('#new_form_operation_description').val("");
  });

app/views/operations/destroy.js.erb
$("#row_<%= dom_id(@operation) %>")
    .animate(
        {opacity: 'hide', height: 'hide'},
        {complete: () => { $("#row_<%= dom_id(@operation) %>").remove(); }}
    );

app/views/operations/edit.html.slim
h1 Editing operation

== render 'form'

=> link_to 'Show', @operation
'|
=< link_to 'Back', maintenance_operations_path(@operation)

app/views/operations/index.html.slim
h1 Listing operations

table
  thead
    tr
      th Maintenance
      th Name
      th Description
      th
      th
      th

  tbody
    - @operations.each do |operation|
      tr
        td = operation.maintenance
        td = operation.name
        td = operation.description
        td = link_to 'Show', operation
        td = link_to 'Edit', edit_operation_path(operation)
        td = link_to 'Destroy', operation, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Operation', new_maintenance_operation_path(@maintenance)

app/views/operations/new.html.slim
h1 New operation

== render 'form'

= link_to 'Back', maintenance_operations_path(@maintenance)

app/views/operations/show.html.slim
p#notice = notice

p
  strong Maintenance:
  = @operation.maintenance
p
  strong Name:
  = @operation.name
p
  strong Description:
  = @operation.description

=> link_to 'Edit', edit_operation_path(@operation)
'|
=< link_to 'Back', maintenance_operations_path(@operation.maintenance)

app/views/operations/update.js.erb
$("#row_<%= dom_id(@operation) %>")
    .animate(
        {opacity: 'hide', height: 'hide'},
        {complete: () => { 
            $("#row_<%= dom_id(@operation) %>")
                .replaceWithPush($("<%= escape_javascript(render @operation) %>").hide())
                .animate({opacity: 'show', height: 'show'});
        }}
    );